{
 "title": "Fitness",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Being Active 24h view",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sedentarySeconds", "legendFormat": "sedentary" },
    { "expr": "activeSeconds", "legendFormat": "active" },
    { "expr": "sleepingSeconds", "legendFormat": "sleeping" },
    { "expr": "highlyActiveSeconds", "legendFormat": "highly active" }
   ]
  },
  {
   "title": "Stress last 24h",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lowStressDuration", "legendFormat": "__auto" },
    { "expr": "mediumStressDuration", "legendFormat": "__auto" },
    { "expr": "highStressDuration", "legendFormat": "__auto" },
    { "expr": "activityStressDuration", "legendFormat": "__auto" },
    { "expr": "restStressDuration", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Heart Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "targets": [
    { "expr": "restingHeartRate", "legendFormat": "Resting" },
    { "expr": "minHeartRate", "legendFormat": "Min Heart" },
    {
     "expr": "lastSevenDaysAvgRestingHeartRate",
     "legendFormat": "7dayAvg"
    },
    { "expr": "maxHeartRate", "legendFormat": "Max HR" }
   ]
  },
  {
   "title": "Body Battery",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "targets": [
    { "expr": "bodyBatteryHighestValue", "legendFormat": "Highest" },
    { "expr": "bodyBatteryLowestValue", "legendFormat": "Lowest" },
    { "expr": "bodyBatteryDuringSleep", "legendFormat": "Sleep" }
   ]
  },
  {
   "title": "Activity Levels",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "sedentarySeconds", "legendFormat": "sedentary" },
    { "expr": "activeSeconds", "legendFormat": "active" },
    { "expr": "sleepingSeconds", "legendFormat": "sleeping" },
    { "expr": "highlyActiveSeconds", "legendFormat": "highly active" }
   ]
  },
  {
   "title": "Oxygen Intake",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    { "expr": "lowestSpo2", "legendFormat": "Low" },
    { "expr": "averageSpo2", "legendFormat": "Average" }
   ]
  },
  {
   "title": "Stress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    { "expr": "maxStressLevel", "legendFormat": "Max" },
    { "expr": "averageStressLevel", "legendFormat": "Average" }
   ]
  }
 ]
}