name: PR Checks

on:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Deps & Run Tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pytest
          
      - name: Helm Template & Lint
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          helm lint ./helm
          helm template ./helm
  